export const seedData = {
  users: [
    {
      id: 'student-demo',
      name: 'Aarav Mehta',
      email: 'student@campusconnect.dev',
      password: 'demo123',
      role: 'student',
      interests: ['Tech', 'Career', 'Cultural'],
      savedEventIds: ['event-1', 'event-4'],
      registeredEventIds: ['event-2'],
      joinedClubIds: ['club-1', 'club-3'],
    },
    {
      id: 'organizer-demo',
      name: 'Naina Sharma',
      email: 'organizer@campusconnect.dev',
      password: 'demo123',
      role: 'organizer',
      interests: ['Tech', 'Entrepreneurship'],
      savedEventIds: [],
      registeredEventIds: [],
      joinedClubIds: ['club-1'],
      managedClubIds: ['club-1'],
    },
  ],
  clubs: [
    {
      id: 'club-1',
      name: 'CodeForge Club',
      category: 'Tech',
      tagline: 'Hackathons, open-source, and late-night debugging energy.',
      description:
        'CodeForge helps students build, ship, and present technical projects through hack nights, coding circles, and real product sprints.',
      membersCount: 248,
      contactEmail: 'codeforge@campusconnect.dev',
      image:
        'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'club-2',
      name: 'Frames & Stories',
      category: 'Creative',
      tagline: 'Photography walks, editing labs, and storytelling workshops.',
      description:
        'A visual storytelling community for campus photographers, editors, and students who want to document real moments beautifully.',
      membersCount: 164,
      contactEmail: 'frames@campusconnect.dev',
      image:
        'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'club-3',
      name: 'LaunchPad Society',
      category: 'Career',
      tagline: 'Career prep, startup conversations, and portfolio reviews.',
      description:
        'LaunchPad connects students with mentors, industry guests, and peers to improve internships, networking, and early-stage startup thinking.',
      membersCount: 196,
      contactEmail: 'launchpad@campusconnect.dev',
      image:
        'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    },
  ],
  events: [
    {
      id: 'event-1',
      title: 'Campus Hack Night',
      summary: 'Build a mini product with teammates and mentors in one focused evening.',
      description:
        'A six-hour collaborative build sprint where students can join teams, brainstorm product ideas, and ship a working prototype with mentor support.',
      category: 'Tech',
      clubId: 'club-1',
      venue: 'Innovation Lab',
      date: '2026-04-25T18:00',
      registrationDeadline: '2026-04-24T23:59',
      capacity: 120,
      registeredCount: 82,
      mode: 'Offline',
      featured: true,
      tags: ['Hackathon', 'Product', 'Teamwork'],
      organizerId: 'organizer-demo',
    },
    {
      id: 'event-2',
      title: 'Resume & LinkedIn Clinic',
      summary: 'One-on-one profile feedback for internship season.',
      description:
        'Students can bring their resumes and LinkedIn profiles for rapid feedback sessions, portfolio review, and recruiter-style screening tips.',
      category: 'Career',
      clubId: 'club-3',
      venue: 'Placement Cell Auditorium',
      date: '2026-04-28T15:30',
      registrationDeadline: '2026-04-27T21:00',
      capacity: 90,
      registeredCount: 61,
      mode: 'Offline',
      featured: true,
      tags: ['Career', 'Resume', 'LinkedIn'],
      organizerId: 'organizer-demo',
    },
    {
      id: 'event-3',
      title: 'Street Photography Walk',
      summary: 'Capture campus stories at golden hour with guided prompts.',
      description:
        'An outdoor photography session focused on framing, movement, composition, and editing-friendly shots for both beginners and experienced members.',
      category: 'Creative',
      clubId: 'club-2',
      venue: 'North Gate and Central Lawn',
      date: '2026-05-02T17:00',
      registrationDeadline: '2026-05-01T18:00',
      capacity: 45,
      registeredCount: 28,
      mode: 'Offline',
      featured: false,
      tags: ['Photography', 'Outdoor', 'Creative'],
      organizerId: 'organizer-demo',
    },
    {
      id: 'event-4',
      title: 'Founder AMA: From Classroom to Startup',
      summary: 'A candid session with alumni founders on early startup lessons.',
      description:
        'An interactive panel where alumni founders share how they validated ideas, built initial teams, found customers, and survived the first year.',
      category: 'Entrepreneurship',
      clubId: 'club-3',
      venue: 'Online',
      date: '2026-05-05T19:00',
      registrationDeadline: '2026-05-05T17:00',
      capacity: 250,
      registeredCount: 142,
      mode: 'Online',
      featured: true,
      tags: ['Startup', 'AMA', 'Alumni'],
      organizerId: 'organizer-demo',
    },
  ],
}

export const categories = ['All', 'Tech', 'Career', 'Creative', 'Cultural', 'Entrepreneurship']
